site_name: ADORe Documentation
nav:
  - About ADORe: README.md
  - Quick Start: quick_start.md
  - Getting Started:
    - Getting Started: getting_started/getting_started.md
    - System Requirements: getting_started/system_requirements.md
    - Prerequisites: getting_started/prerequisites.md
    - Installing Docker: getting_started/installing_docker.md
    - Building ADORe: getting_started/building_adore.md
  - Technical Reference Manual:
    - Documentation: system_and_development/documentation.md
    - Submodules: modules.md
    - Troubleshooting: problems_and_solutions.md
    - Licensing: licensing.md
    - Contributing: CONTRIBUTING.md
    - Style Guide: styleguide.md
  - Contact: contact.md

theme:
  name: material 
  logo: ../img/logo.png
  favicon: ../img/favicon.ico
  features:
    - content.code.copy

plugins:
  - search
  # - pdf-export
