name: CI

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Init
        run: |
          df -h
          sudo apt-get update

      - name: Maximize free space
        id: maximize-space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Freespace Check
        run: |
          df -h
          REQUIRED_FREE_SPACE=25
          free_space=$(df -h . | awk '{print $4}' | grep "G")
          free_space="${free_space%G}"
          if [ -z "$free_space" ]; then
              echo "ERROR: free_space variable is empty or not set." >&2
              exit 1
          fi
          df -h
          echo "Free space (required): ${REQUIRED_FREE_SPACE} GB"
          echo "Free space (available): ${free_space} GB"
          if (( REQUIRED_FREE_SPACE > free_space )); then
              echo "ERROR: Insufficient free space: ${free_space} GB available, ${REQUIRED_FREE_SPACE} GB required." >&2
              exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install requirements
        run: |
          df -h
          sudo apt-get update
          sudo apt-get install -y make

      - name: Build vendor libraries
        run: |
          echo "Building vendor..."
          make build_vendor_libraries 
          make save || true

      - name: Build ADORe CLI
        run: |
          echo "Building ADORe CLI core..."
          make load || true
          make build_adore_cli_core
          echo "Building ADORe CLI..."
          make build_adore_cli
          make save || true

      - name: Test ROS2 installation 
        run: |
          echo "Testing the ROS 2 installation in the ADORe CLI..."
          make load || true
          make test_ros2_installation
          make save || true

      - name: Build user libraries
        run: |
          make load || true
          echo "Building user libraries..."
          make build_user_libraries
          make save || true

      - name: Build ROS nodes
        run: |
          make load || true
          echo "Building nodes..."
          make build_ros_nodes
          make save || true

      - name: Build Services
        run: |
          make load || true
          echo "Building services..."
          make build_services
          make save || true

      - name: CI Test
        run: |
          df -h
          make ci_test
      
      - name: Documentation Lint
        run: |
          cd documentation
          make lint

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: .log
        if: always()

